### ISSUE TITLE
Question: What's the best way to save the world state and restore it?

### ISSUE THREAD

**Issue by sz-po** [dominion-dev/dominion-ecs-java#177]
What's the best way to save the state and restore it? I can iterate over all entities, but how to recreate the state so that the IDs of the new entities are the same as in the saved state?

**Comment by enricostara** [comment]
Hi @sz-po ,
sorry for the delay in replying.

There is no specific way directly supported by the library regarding save/restore of entities.
At this moment, It's up to you how you serialize/deserialize the state of your entities and what framework/data-format you use to get the job done.
Only one thing you can consider without any doubt: you don't need to restore entities keeping the same id! the id should always be considered private and you shouldn't care about its value.

**Comment by sz-po** [comment]
> Only one thing you can consider without any doubt: you don't need to restore entities keeping the same id! the id should always be considered private and you shouldn't care about its value.

Thank You from quick reply!

So maybe I do some missunderstanding, but how I should store references between entities?

**Comment by enricostara** [comment]
Let's say you have a component referencing another entity. When you serialize consider to transform the entity reference as a reference of array of its components and when you deserialize transform back as a reference of a new entity having the original array of components deserialized as well. This pattern can be replicated at any depth .

**Comment by enricostara** [comment]
I'm closing this issue, please open a new one if you need further clarification.
