### ISSUE TITLE
Support for optional, not, relationships etc

### ISSUE THREAD

**Issue by pfeodrippe** [dominion-dev/dominion-ecs-java#184]
Hi, great lib! I’m using it for my Clojure small game and it has been a breeze :D

Do you think that we could support optional, not, relationships (as in https://ajmmertens.medium.com/building-games-in-ecs-with-entity-relationships-657275ba2c6c) in Dominion? 

Keep the good work o/

**Comment by pfeodrippe** [comment]
Oh yeah, forgot, not is already supported by without, but I guess you understood what I have meant o/

**Comment by pfeodrippe** [comment]
One other stuff, I guess it's feasible to get all the components in the world, right? Using the nodes and such

**Comment by enricostara** [comment]
Hi @pfeodrippe ,

to get all the dominion entities yo can use the `Dominion.findAllEntities()` method.

Please open a new issue if anything else is unclear, thanks!

**Comment by pfeodrippe** [comment]
> Hi @pfeodrippe ,
> 
> to get all the dominion entities yo can use the `Dominion.findAllEntities()` method.
> 
> Please open a new issue if anything else is unclear, thanks!

Hi Enrico, thanks!

So a component is an entity in Dominion?

For the original question (optional, not etc), do you know if it’s feasible?
